name: CI

on:
  push:
    branches: [main, chore/ci-setup]
  workflow_dispatch:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
#          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: |
          uv sync
          uv pip install .
          uv pip install .[dev]

      - name: Run tests
        run: |
          uv run pytest

      - name: Lint with flake8
        run: |
          uv run flake8 .